"""empty message

Revision ID: fda7d7cca9e
Revises: None
Create Date: 2015-11-28 21:17:43.531149

"""

# revision identifiers, used by Alembic.
revision = 'fda7d7cca9e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kegg_reactions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('organism', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kegg_reactions')
    ### end Alembic commands ###
